### ISSUE TITLE
Interpolation warnings

### ISSUE THREAD

**Issue by blcetux** [jpamies/terraform-aws-certificate#10]
Hi,

We are having interpolation warnings such as:

```
Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/<REDACTED>/outputs.tf line 3, in output "arn":
   3:   value       = "${aws_acm_certificate_validation.this.certificate_arn}"
```
Can you fix it?

Regards,
Bruno Costa

**Comment by jpamies** [comment]
Hi @blcetux 

Which version of terraform and provider are you using?

**Comment by jpamies** [comment]
Fixed in https://github.com/jpamies/terraform-aws-certificate/releases/tag/1.1.1 !
thanks @blcetux
